name: Increment Version
on:
  workflow_dispatch:
    inputs:
      versionIncrementType:
        description: 'The type of increment'
        type: choice
        required: true
        options:
          - MAJOR
          - MINOR
          - PATCH
      versionIncrementBranch:
        description: 'The branch where the version increment will be committed and pushed'
        required: true
        default: 'main'
jobs:
  incrementVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_DEVOPS_CHANNEL_WEBHOOK }}
          title: "Start incrementing version of rdf-kafka-sink-connector"
          color: 0xffed2b
          username: GitHub Actions

      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # https://github.com/actions/setup-java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run incrementVersion command
        run: ./gradlew incrementVersion --versionIncrementType=${{ github.event.inputs.versionIncrementType }} --versionIncrementBranch=${{ github.event.inputs.versionIncrementBranch }}
        env:
          gitUserEmail: 'github.bot@geovistory.org'
          gitUserName: 'geovbot'

      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_DEVOPS_CHANNEL_WEBHOOK }}
          title: "Done: Incrementing version of rdf-kafka-sink-connector"
          description: ""
          color: 0x0000ff
          username: GitHub Actions
