name: Publish package to GitHub Packages
on: workflow_dispatch
  #release:
   # types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_DEVOPS_CHANNEL_WEBHOOK }}
          title: "Start publishing new package of rdf-kafka-sink-connector"
          color: 0xffed2b
          username: GitHub Actions

      - name: Checkout code 
        uses: actions/checkout@v3
        
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        
      - name: Build JAR
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        
      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GEOVBOT_PAT }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_DEVOPS_CHANNEL_WEBHOOK }}
          title: "Done: publishing of new package of rdf-kafka-sink-connector"
          description: ""
          color: 0x0000ff
          username: GitHub Actions