name: Releases

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      # Set VERSION_NAME
      - run: echo "VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_ENV

      - name: Prints version information
        run: echo Version is '${{ env.VERSION_NAME }}'

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION_NAME }}